[package]
name = "free_pfp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mysql = "*"
time = { version = "0.3.31", features = [] }